// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_9BDPFKsitmM9mHOkF1YG7qvWHnSVg4',
    appId: '1:209306951839:web:f268a6aa6cfa03a20e02aa',
    messagingSenderId: '209306951839',
    projectId: 'flora-vision-5db05',
    authDomain: 'flora-vision-5db05.firebaseapp.com',
    storageBucket: 'flora-vision-5db05.firebasestorage.app',
    measurementId: 'G-TSQMWTM08R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw1zIX0wQJTFqyxy8iwOJjWUf4MKuV-WY',
    appId: '1:209306951839:android:b6a6018c308020e90e02aa',
    messagingSenderId: '209306951839',
    projectId: 'flora-vision-5db05',
    storageBucket: 'flora-vision-5db05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjx0tLodDABSr-8jp6MCNCvSPchtoaWwg',
    appId: '1:209306951839:ios:7117e81109f8ed9e0e02aa',
    messagingSenderId: '209306951839',
    projectId: 'flora-vision-5db05',
    storageBucket: 'flora-vision-5db05.firebasestorage.app',
    iosBundleId: 'com.example.floraVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjx0tLodDABSr-8jp6MCNCvSPchtoaWwg',
    appId: '1:209306951839:ios:7117e81109f8ed9e0e02aa',
    messagingSenderId: '209306951839',
    projectId: 'flora-vision-5db05',
    storageBucket: 'flora-vision-5db05.firebasestorage.app',
    iosBundleId: 'com.example.floraVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_9BDPFKsitmM9mHOkF1YG7qvWHnSVg4',
    appId: '1:209306951839:web:686b641f701ceb6d0e02aa',
    messagingSenderId: '209306951839',
    projectId: 'flora-vision-5db05',
    authDomain: 'flora-vision-5db05.firebaseapp.com',
    storageBucket: 'flora-vision-5db05.firebasestorage.app',
    measurementId: 'G-BE7BKV2WTE',
  );
}
